### ISSUE TITLE
ATS instal fail, missing dependencies

### ISSUE THREAD

**Issue by vgrme** [jeredfloyd/rpm-trafficserver#1]
When I try to install it, I see the below dependencies are missing and the installation therefore is failing.
hwloc-libs-2.2.0-3.el8.x86_64.rpm
hwloc-2.2.0-3.el8.x86_64.rpm

**Comment by jeredfloyd** [comment]
Let's continue this over in the trafficserver ticket: https://github.com/apache/trafficserver/issues/6855#issuecomment-1159079955

hwloc/hwloc-libs are part of BaseOS so yum/dnf should automatically resolve those dependencies.  Are you trying to install a bare rpm?

**Comment by vgrme** [comment]
If it is part of the BaseOS then the installation should not fail.
I also looked up one of those mirrors and dont see these rpms.
Will this be made available on RHEL's official RPM browser ? 
Should I do a yum/dnf update and then try yum install trafficserver. 
Can you try to install on your box and let me know what you see.

**Comment by jeredfloyd** [comment]
Can't reproduce; will request more information again in trafficserver ticket.
